# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addStu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

'''This file gets executed when Add student button is clicked
   It opens a dialog box where it asks for roll number and then captures image on clicking the Capture image button
'''

from PyQt5 import QtCore, QtGui, QtWidgets
import cv2
import os
from capImg import capImg

path = 'studentImages'
images = []
#this list stores the roll numbers of the student images
classNames = []
myList = os.listdir(path)
for cl in myList:
        curImg = cv2.imread(f'{path}/{cl}')
        images.append(curImg)
        classNames.append(os.path.splitext(cl)[0])
#print(classNames)

class Ui_Dialog(object):
    
    #This function checks the constraints fixed on the given roll number
    #and opens camera to capture the student image
    def openCapImg(self):
            self.fname = self.rollInput.text()
            if(self.fname==''):
                    self.errorLab.setText("Enter your roll number!")
            elif(self.fname in self.fname in classNames):
                    self.errorLab.setText("Student already exists!")

            else:
                    self.errorLab.setText("")
                    classNames.append(self.fname)
                    print("ans:",self.fname)
                    capImg(self.fname)
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(568, 439)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(9, 9, 551, 421))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0.168, y1:0.267, x2:0.995, y2:0.983, stop:0 rgba(209, 104, 165, 255), stop:1 rgba(255, 172, 255, 255))}")
        self.widget.setObjectName("widget")
        self.rollLabel = QtWidgets.QLabel(self.widget)
        self.rollLabel.setGeometry(QtCore.QRect(40, 80, 181, 61))
        self.rollLabel.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.rollLabel.setObjectName("rollLabel")
        self.rollInput = QtWidgets.QLineEdit(self.widget)
        self.rollInput.setGeometry(QtCore.QRect(260, 90, 241, 41))
        self.rollInput.setStyleSheet("QLineEdit{\n"
"color:rgb(0, 0, 0);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px;\n"
"padding:10px\n"
"}")

        self.rollInput.setInputMask("")
        self.rollInput.setText("")
        self.rollInput.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.rollInput.setClearButtonEnabled(True)
        self.rollInput.setObjectName("rollInput")
        self.errorLab = QtWidgets.QLabel(self.widget)
        self.errorLab.setGeometry(QtCore.QRect(280, 150, 201, 20))
        self.errorLab.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.errorLab.setText("")
        self.errorLab.setObjectName("errorLab")
        self.capImgBtn = QtWidgets.QPushButton(self.widget)
        self.capImgBtn.setGeometry(QtCore.QRect(140, 230, 261, 51))
        self.capImgBtn.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color:rgb(255, 255, 255);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 0, 0)\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 0)\n"
"}")
        self.capImgBtn.setObjectName("capImgBtn")
        #capture image button click
        self.capImgBtn.clicked.connect(self.openCapImg)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.rollLabel.setText(_translate("Dialog", "ROLL NUMBER"))
        self.rollInput.setPlaceholderText(_translate("Dialog", "ENTER ROLL NUMBER"))
        self.capImgBtn.setText(_translate("Dialog", "CAPTURE IMAGE"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
