# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

'''This is the main file of the project
   On executing this file main window of the application opens
'''

from PyQt5 import QtCore, QtGui, QtWidgets
from addStd import Ui_Dialog
from AttendanceMain import takeAttendance

class Ui_MainWindow(object):

    #This function opens the Add Student dialog box when Add student button is clicked
    def openWindow(self):
        self.window =  QtWidgets.QDialog()
        self.ui =  Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    #This function opens the camera to take attendance
    def takeAtd(self):
            takeAttendance()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 666)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-11, -1, 1091, 721))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0.168, y1:0.267, x2:0.995, y2:0.983, stop:0 rgba(209, 104, 165, 255), stop:1 rgba(255, 172, 255, 255))}")
        self.widget.setObjectName("widget")
        self.mainheading = QtWidgets.QLabel(self.widget)
        self.mainheading.setGeometry(QtCore.QRect(190, 30, 711, 71))
        self.mainheading.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.mainheading.setObjectName("mainheading")
        self.icon = QtWidgets.QLabel(self.widget)
        self.icon.setGeometry(QtCore.QRect(20, 20, 101, 91))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("../pageImages/mainIcon.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.mainImg = QtWidgets.QLabel(self.widget)
        self.mainImg.setGeometry(QtCore.QRect(630, 140, 341, 461))
        self.mainImg.setText("")
        self.mainImg.setPixmap(QtGui.QPixmap("../pageImages/mainImg2.png"))
        self.mainImg.setScaledContents(True)
        self.mainImg.setObjectName("mainImg")
        self.addStdBtn = QtWidgets.QPushButton(self.widget)
        self.addStdBtn.setGeometry(QtCore.QRect(170, 220, 261, 51))
        self.addStdBtn.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color:rgb(255, 255, 255);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 0, 0)\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 0)\n"
"}")
        self.addStdBtn.setObjectName("addStdBtn")
        #add student button click
        self.addStdBtn.clicked.connect(self.openWindow)
        self.atdBtn = QtWidgets.QPushButton(self.widget)
        self.atdBtn.setGeometry(QtCore.QRect(170, 370, 261, 51))
        self.atdBtn.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color:rgb(255, 255, 255);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 0, 0)\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 0)\n"
"}")
        self.atdBtn.setObjectName("atdBtn")
        #take attendance button click
        self.atdBtn.clicked.connect(self.takeAtd)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainheading.setText(_translate("MainWindow", "SMART ATTENDANCE SYSTEM USING FACE RECOGNITION"))
        self.addStdBtn.setText(_translate("MainWindow", "ADD STUDENT"))
        self.atdBtn.setText(_translate("MainWindow", "TAKE ATTENDANCE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
